/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.35 from the
 * contents of Eye.xs. Do not edit this file, edit Eye.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Eye.xs"
